### PR TITLE
fix: persist anonymous token after auth login and uninstall

### PR DESCRIPTION
**Pull request by radulucut**

### CODE REVIEW

**Comment by radulucut** [comment]
@MartinKolarik are anonymous tokens live yet?

**Comment by MartinKolarik** [comment]
Should be live but hard to test without #72. I'll merge that one soon.

**Comment by MartinKolarik** [comment]
I just checked and it's live but nobody used it yet so there's nothing to migrate 😄

**Comment by radulucut** [comment]
I added it just in case

**Pull request merged**
